# LOGGING
logging:
  file: /var/log/springboot/exception-handling
  level: 
    org.springframework.web: DEBUG


server:
  tomcat:
    access-log-enabled: true
    access-log-pattern: "%h %l %u %t \"%r\" %s %b %D \"%{Referer}i\" \"%{User-agent}i\""
    basedir : /var/log/springboot
